### PR TITLE
Added setSpeed() to componentDidMount()

### PR DESCRIPTION
**Pull request by andreragsilva**
Related to issue #48

### CODE REVIEW

**Comment by rageofflames** [comment]
`setSpeed()` should probably be removed from `componentWillUpdate()`

**Comment by rageofflames** [comment]
Is `setSpeed()` still needed in `componentWillUpdate()`?

**Comment by Jefoss** [comment]
@chenqingspring can you please review this change? its still relevant imo

**Comment by tomreposify** [comment]
@rageofflames did this change make it work?

**Comment by rageofflames** [comment]
@tomreposify it worked for me, you can also check the fork I created, there is a branch with the change https://github.com/rageofflames/react-lottie

Maybe we should start migrating issues to the fork to try and maintain this lib and then find a way to merge it

**Comment by andreragsilva** [comment]
Thank you @chenqingspring 😃

**Pull request merged**
