### PR TITLE
feat: Allow custom styles (helps fix #18)

### LINKED ISSUE #18: controlling padding
hello ! 
I downloaded some lottie files from the platform but some of these have a really huge padding. any idea how to control that ?

### PR DESCRIPTION
**Pull request by SahajR**
Commit is self-explanatory

### CODE REVIEW

**Comment by karolfalkiewicz** [comment]
👍 I want to use styled components wrapper for styling but no can do 😢

**Comment by MonsieurWave** [comment]
Would be a great plus!

**Comment by MonsieurWave** [comment]
Would be a great plus!

**Comment by Sulsummer** [comment]
@chenqingspring Will you add the feature as @karolfalkiewicz said pls?  😄

**Pull request merged**
