### PR TITLE
Fixed eventListeners not being removed

### PR DESCRIPTION
**Pull request by jwfwessels**
Hi,
I discovered a bug that occurred when you replace that animation data multiple times as well as switch between different sets of event listeners based on the animation.

On further investigation, I realised it was probably because events do not get deregistered before the animation object gets reassigned.

I refactored index.js to add two class methods `registerEvent` and `deregisterEvent`.
Then in the `componentWillUpdate` lifecycle method if the animation has changed It now deregisters events before destroying animation object and then creates new event listeners if applicable.

I also fleshed out your readme a bit regarding *Props* that the Lottie component can receive.

Let me know if you think I should do anything differently.
Cheers
J

### CODE REVIEW

**Comment by chenqingspring** [comment]
Thanks for fixing this 👍

**Comment by jwfwessels** [comment]
@chenqingspring 
hey man,
changed from my fork to tag 2.3.0.

noticed it wasn't behaving as expected. noticed you made some more changes in [61fb09e](https://github.com/chenqingspring/react-lottie/commit/61fb09e6d9ed748487425308843b44a9f79a1997). Not sure what undefined event listener issue you were trying to address. but the code doesn't work now.

let me know if you need some more help with this repo.

**Comment by chenqingspring** [comment]
@jwfwessels  You're right, I made a bug after refactoring code.. I'll fixing it soon

Thanks for reminding me this!

**Comment by chenqingspring** [comment]
@jwfwessels I released v0.2.4, can you help me check again?

And If you want give me a hand by adding a demo into storybook, that will be good :-)

**Comment by jwfwessels** [comment]
Seems to be working again 🕺 

Yeah, sure i'll add a storybook demo.

**Comment by chenqingspring** [comment]
Awesome! Thanks :)

**Pull request merged**
